### ISSUE TITLE
HLAE Loader Failed | Code: 2001

### ISSUE THREAD

**Issue by steels111111** [ripieces/advancedfx#740]
When I launch CS:GO for the first it shows an error:

I have looked at previous reports on this issue, and none of the suggested fixes work. No program has been set to "run as administator" and I do not have an anti-cheat client such as ESEA and FACEIT installed on my computer.

![Capture](https://user-images.githubusercontent.com/96333607/146636205-9bbbb199-e713-4588-8fbf-5123813695db.PNG)
![Capture2](https://user-images.githubusercontent.com/96333607/146636211-fa75d3fd-779a-4761-ae88-f16191fc13dc.PNG)

```
AfxError #2001: 
Title: Loader failed.Description: System.Runtime.Serialization.SerializationException: End of Stream encountered before parsing was completed.
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at advancedfx.injector.interop.Formatter.System.Runtime.Serialization.IFormatter.Deserialize(Stream serializationStream)
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)Inner exception: {0}```

**Comment by dtugend** [comment]
Which Anti-Virus do you use?
Something is blocking the communication between HLAE and it's injector.exe maybe.

Edit: Please also check the path to csgo.exe is actually correct / works (enter it in explorer to test):

```
 2001

    Anti-cheat or antivirus software is blocking HLAE
    The path to the game .exe is empty or incorrect in the HLAE launcher settings
```

**Comment by steels111111** [comment]
I use Trend Micro Maximum Security.

Edit: The path is correct because CS:GO opens but HLAE itself doesn't work (cant use mirv_ commands etc.)

**Comment by dtugend** [comment]
We have had Anti Virus with behaviour blocking blocking too much in the past. Can you add an exception in the behaviour blocking feature for the injector.exe that is in same folder like HLAE.exe (the one in x64 subfolder does not matter, it's for 64 bit process, CS:GO needs the 32 bit one)? Or otherwise add an exception for it and test again?

Edit: If there's no injector.exe next to HLAE.exe the antivirus might have deleted it, though that should have resulted in a different error code usually.

Sorry for late reply.

**Comment by steels111111** [comment]
Thank you! I added the HLAE folder as an exception and now everything is working fine.
